Filter by query and date formatting
DenverCoder1/jct-discord-bot pull request #77
Opened 2021-02-05 11:31 UTC by DenverCoder1

Closes #76

Added query parameter to events.list

Also changed date formatting

Before: `Mar 22 2021 8:30 AM - Mar 22 2021 12:00 PM`

New: `Mon, Mar. 22 8:30 AM - 12:00 PM`

2021-02-05 12:01 UTC, abrahammurciano requested changes

2021-02-05 14:09 UTC, DenverCoder1 commented
Fixes #75

Replaces channel mentions with course names

2021-02-05 14:45 UTC, abrahammurciano approved these changes

2021-02-05 14:45 UTC, abrahammurciano commented on modules/calendar/cog.py
>  		**<Start Time>**: The start time of the event.
Date and/or time

2021-02-06 16:33 UTC, abrahammurciano approved these changes

2021-02-06 17:31 UTC, merged